### ISSUE TITLE
[BUG]: #Tredence - Transpile adds NULLS FIRST, NULLS LAST as extra in Databricks SQL output for Snowflake order by statement

### ISSUE THREAD

**Issue by Mailendiran98** [databrickslabs/remorph#1034]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Category of Bug / Issue

TranspileParserError

### Current Behavior

**Input**

select names, salary from employee
order by nams,salary desc

**Transpile output:**

SELECT names,salary FROM employee
ORDER BY
  nams NULLS LAST,
  salary DESC NULLS FIRST

### Expected Behavior

select names, salary from employee
order by nams,salary desc

### Operating System

Windows

### Version

latest via Databricks CLI

**Comment by sriram251-code** [comment]
In Snowflake and Databricks SQL, the default sort behavior for NULL values is indeed different, which can lead to inconsistencies if you're moving between these platforms or trying to maintain standard behavior across both.

Default Sort Behavior
Snowflake:
ASC (Ascending): NULLS sort last
DESC (Descending): NULLS sort first
https://docs.snowflake.com/en/sql-reference/constructs/order-by#usage-notes

Databricks:
ASC (Ascending): NULLS sort first
DESC (Descending): NULLS sort last
https://docs.databricks.com/en/sql/language-manual/sql-ref-syntax-qry-select-orderby.html#parameters

To mimic Snowflake's behavior in Databricks SQL, we add explicit sorting conditions:
For ascending order: NULLS LAST
For descending order: NULLS FIRST
