### ISSUE TITLE
Source Adapter and Recon Config

### ISSUE THREAD

**Issue by sundarshankar89** [databrickslabs/remorph#113]
Build a Source Connector Adapter that can connect to multiple sources.

- Extract Data from source
- Extract Schema from Source
- Extract Schema from Databricks
- Get Column Transformation List

**Comment by ganeshdogiparthi-db** [comment]
Snowflake Code and Test cases completed.
Databricks Code and Test cases completed.
Oracle code is done. Waiting on test cases.
