### ISSUE TITLE
[BUG]: #Tredence . If we have single file for multiple DDL’s & if there is error in any DDL, then whole file is getting skipped

### ISSUE THREAD

**Issue by Mailendiran98** [databrickslabs/remorph#1185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Category of Bug / Issue

TranspileParserError

### Expected Behavior

It should skip the particular corrupted DDL, however rest of the DDL should be converted properly

### Operating System

Windows

### Version

latest via Databricks CLI

**Comment by aman-db** [comment]
@Mailendiran98, please provide us with an example that will allow us to replicate the issue on our end.
