### ISSUE TITLE
[LCA]: Ability replace Lateral Alias with actual column name and Expression

### ISSUE THREAD

**Issue by sundarshankar89** [databrickslabs/remorph#1222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Category of feature request

Transpile

### Problem statement

Given the following Snowflake SQL:
```
SELECT column_a as customer_id
FROM mytable
WHERE customer_id = '123'
```

The following Spark SQL should be returned because of the different alias scoping used in Spark SQL

``` 
SELECT column_a as customer_id
FROM mytable
WHERE column_a = '123'
```

https://www.databricks.com/blog/introducing-support-lateral-column-alias

### Proposed Solution

NA

**Comment by sundarshankar89** [comment]
@ericvergnaud  this might be an issue.

**Comment by sundarshankar89** [comment]
more such examples are present under `lca_utils.py` on how we tackle we haven't covered all combinations but you can refer how we do preprocessing using python prototype.

**Comment by ericvergnaud** [comment]
@sundarshankar89 re the output, did you mean:

```
SELECT column_a as customer_id
FROM mytable
WHERE column_a = '123'
```

?

**Comment by sundarshankar89** [comment]
Just edited the description.

Also checkout `test_lca_utils.py` it has few more examples with LCA in sourcesystem.

**Comment by asnare** [comment]
> Given the following Snowflake SQL:
> 
> ```
> SELECT column_a as customer_id
> FROM mytable
> WHERE customer_id = '123'
> ```
> 
> The following Spark SQL should be returned because of the different alias scoping used in Spark SQL
> 
> ```
> SELECT column_a as customer_id
> FROM mytable
> WHERE column_a = '123'

We need to be careful here because there's a problem with using this[^1] as a universal strategy. It's fine for simple column references, but if it's an expression then the semantics can be altered because:
 - Expressions aren't always deterministic.
 - Aliases imply 'evaluate once' semantics.
 - This can lead to the expression evaluating differently during projection and predicate evaluation.

A more accurate strategy would be something like:
```sql
SELECT expr_a AS customer_id
FROM mytable
WHERE customer_id = '123'
```
becomes
```sql
SELECT customer_id
FROM (
  SELECT expr_a AS customer_id
  FROM mytable
)
WHERE customer_id = '123'
```

This is also not entirely problem-free: there are some challenges with (unqualified) column resolution when there are columns and aliases with the same name. I _think_ the semantics for SnowFlake are that column names have precedence over aliases but am not entirely sure. This should be solved by using qualified names where possible. A more robust version would therefore be:
```sql
SELECT xxx.customer_id
FROM (
  SELECT expr_a AS customer_id
  FROM mutable
) xxx
WHERE xxx.customer_id = '123'
```

[^1]: Expression substitution.

**Comment by sundarshankar89** [comment]
@asnare why not this, or is this too simplistic where expr_a can be non window functions?

```
  SELECT expr_a AS customer_id
  FROM mytable
WHERE expr_a = '123'

**Comment by sundarshankar89** [comment]
also I don't know what should be the behaviour.

```
select substr(zip, 1, 3) as zip
from mytable
zip = 10;
