### ISSUE TITLE
[FEATURE]: Multiplexer - propose design

### ISSUE THREAD

**Issue by ericvergnaud** [databrickslabs/remorph#1253]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Category of feature request

Transpile

### Problem statement

See https://docs.google.com/presentation/d/1qLNsIwrBb97iSwDortmAqd3WyxKU0HerXsNg8j_yKAU/edit?usp=sharing

### Proposed Solution

See https://docs.google.com/presentation/d/1qLNsIwrBb97iSwDortmAqd3WyxKU0HerXsNg8j_yKAU/edit?usp=sharing

**Comment by jimidle** [comment]
@gueniai @ericvergnaud Can we either use Google docs and follow the engineering format, or use markdown in a PR for specs? I have to request access to the slides and I don't think slides are good format for this type of thing.

**Comment by gueniai** [comment]
@jimidle, as it stands right now, this is the step before the design doc can even begin. The slides are more aligned with our product requirements document (PRD) process, talking about the motivation and clarifying high-level requirements.
