### ISSUE TITLE
[TECH DEBT]: Fix `ORDER BY` precedence in TSQL grammar

### ISSUE THREAD

**Issue by asnare** [databrickslabs/remorph#1256]
### Current Behavior

The TSQL grammar currently allows for `ORDER BY` expressions between set operations (`INTERSECT`, `EXCEPT`, `UNION`) and associates them with the intermediate expression.

### Expected Behavior

For TSQL the `ORDER BY` clause is applied _after_ all the set operations: it should not be attached to the immediately preceding expression. That is:

```sql
SELECT 10
UNION
SELECT 20
ORDER BY 1
```
is equivalent to:
```sql
(SELECT 10
 UNION
 SELECT 20)
ORDER BY 1
```
and _not_ this as currently is the case:
```sql
(SELECT 10)
UNION
(SELECT 20
 ORDER BY 1)
```

Reference: https://learn.microsoft.com/en-us/sql/t-sql/language-elements/set-operators-union-transact-sql?view=sql-server-ver16#c-using-union-of-two-select-statements-with-order-by

Further to this, the following is erroneous:
```sql
SELECT 10
ORDER BY 1
UNION
SELECT 10
ORDER BY 2
```

_The documentation refers to this as _incorrect_ which is a little ambiguous: it's open to read that rather than being an error it could be accepted but pointless. Testing shows that it is treated as an error:_
```sql
select 10
order by 1
union
select 20
order by 1 desc
```
_yields_
```
Failed to execute query. Error: Incorrect syntax near the keyword 'union'.
```

### Functional Test

This functional test should pass if `ORDER BY` has been implemented correctly.

```sql
--
-- ORDER BY appears at the end of a sequence of set operations, and applies to the result of the set operation.
--
-- tsql sql:

SELECT 1
UNION
SELECT 2

ORDER BY 1 DESC; -- Applies to the complete UNION, not just the final expression.

-- databricks sql:
((SELECT 1)
 UNION
 (SELECT 2))
ORDER BY 1 DESC;
```

**Comment by asnare** [comment]
Some playing around to explore some of the `ORDER BY` behaviour…

```sql
(SELECT 10 ORDER BY 1) UNION SELECT 20
```
`Failed to execute query. Error: Incorrect syntax near the keyword 'UNION'.`

Let's try a subquery:
```sql
SELECT * FROM (SELECT 10 ORDER BY 1) UNION SELECT 20
```
`Failed to execute query. Error: The ORDER BY clause is invalid in views, inline functions, derived tables, subqueries, and common table expressions, unless TOP, OFFSET or FOR XML is also specified.`

Drop in a `TOP` and it's still not happy, we're back to the original error:
```sql
SELECT * FROM (SELECT TOP(1) 10 ORDER BY 1) UNION SELECT 20
```
`Failed to execute query. Error: Incorrect syntax near the keyword 'UNION'.`

Extract to a CTE though and it's okay:
```sql
WITH x AS (SELECT TOP(1) 10 AS n ORDER BY 1)
SELECT * FROM x UNION SELECT 20
```
| n  |
|---:|
| 10 |
| 20 |

**Comment by jimidle** [comment]
Cool. Good research, which will help me rejig the grammar to support teh correct precedence (there basically isn't any right now!).

Just one point to make in case it isn't me that changes the grammar: 

We decided very early on to assume that the SQL given to us is syntactically and semantically correct, as we are a transpiler - garbage in, garbage out. So, we don't need to report contextual/semantic errors like the TSQL engine will. Hence we don't try to write grammar rules that tortuously enforces syntax. One should not write grammars like this anyway, we write a grammar that accepts anything that looks like it could be valid, then apply a semantic pass to throw out errors like 'not valid in views' - which we won't do in the transpiler of course as the input code should already be verified accurate.
