### ISSUE TITLE
[FEATURE]: Snowflake conversion from TO_NUMERIC without format

### ISSUE THREAD

**Issue by justinkolpak-databricks** [databrickslabs/remorph#1316]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Category of feature request

Transpile

### Problem statement

Snowflake's `TO_NUMERIC` function is unable to be transpiled into Spark SQL using Remorph, specifically if the optional format, precision, and scale are not set. Similar functionally has been addressed for `TO_NUMBER` in [this PR](https://github.com/databrickslabs/remorph/pull/172)

### Proposed Solution

`TO_NUMERIC` functions without format, precision, or scale to be transpiled into Spark SQL without issue.

**Comment by aman-db** [comment]
@justinkolpak-databricks Could you please provide the exact query that is failing?

**Comment by justinkolpak-databricks** [comment]
```
SELECT  TO_NUMERIC(prn) AS prn
FROM
   <table> AS t
```

Results in error message:
`ParserError(file_name='/Users/justin.kolpak/remorph/snowflake_sql/greenlight_test1.sql', exception='Error Parsing expression CAST(prn AS DOUBLE):\n                         * `format`: is required in Databricks [mandatory]\n                         * `precision` and `scale`: are considered as (38, 0) if not specified.\n                      ')
`

**Comment by aman-db** [comment]
@justinkolpak-databricks which version you are using it seems to be working fine for me 
input query - 
`SELECT  TO_NUMERIC(prn) AS prn
FROM
   tst_table AS t
`
output - 
`
SELECT
  CAST(prn AS DECIMAL(38, 0)) AS prn
FROM tst_table AS t
;
`

**Comment by aman-db** [comment]
this works fines with version(v0.9.0).
