### ISSUE TITLE
Installation doesn't automatically download blueprint 

### ISSUE THREAD

**Issue by nsenno-dbr** [databrickslabs/remorph#153]
Version 0.1.3 

When running the CLI tool after installation, it complains that I don't have databricks.labs.blueprint installed. It should either download the dependency as part of the install process, or warn us that we should be in a virtual environment and run the pip install -r requirements.txt in that environment 

![image](https://github.com/databrickslabs/remorph/assets/59416974/a8ed68b6-bcae-48ce-953d-29f14d3be455)

**Comment by sundarshankar89** [comment]
@nfx  does this require to go through remorph install or explicit install of blueprint is required?

**Comment by sundarshankar89** [comment]
@nsenno-dbr is not able to reproduce this in the latest release can you recheck

**Comment by nsenno-dbr** [comment]
@sundarshankar89 I haven't had this issue since. My old laptop is just old and full of python debris

**Comment by nfx** [comment]
fixed on CLI level
