### ISSUE TITLE
Common Snowflake syntax conversion errors

### ISSUE THREAD

**Issue by dougspadotto** [databrickslabs/remorph#165]
I believe these 2 Snowflake syntax detection and conversion should be covered by remorph and they're still returning errors:

1. When the Snowflake code had setting options like “!set exit_on_error=true”, remorph returns an error. We should just warn, comment out, or remove the line and progress.

2. When passing a parameter, for example, MERGE INTO &SCHEMA_NAME.ATABLE T … remorph also gives an error with the unexpected ‘&’. We should convert to the Databricks SQL way of passing parameters, not only for schema/table names but also on values like DATE = &INPUT_DATE.

**Comment by sundarshankar89** [comment]
@dougspadotto variables are represented with `$` in snowflake not `&' 
https://docs.snowflake.com/en/sql-reference/session-variables
snow the query works when `$` is used

**Comment by dougspadotto** [comment]
@sundarshankar89 , when using variable substitution, the & syntax is utilized. Please check this out: https://docs.snowflake.com/en/user-guide/snowsql-use#enabling-variable-substitution

 I'm also adding an example of a working script for reference.
<img width="756" alt="image" src="https://github.com/databrickslabs/remorph/assets/5835211/32ae71a3-6d8a-479e-9257-66c3c2e7de64">

**Comment by dougspadotto** [comment]
@sundarshankar89 , is there any plan to support variable substitution? It seems to be a matter of adding & as a  PARAMETER_TOKEN at remorph/src/databricks/labs/remorph/snow/databricks.py, but I don't want to do a PR because I haven't investigated deeply any other consequences of this change.

**Comment by sundarshankar89** [comment]
we will pick this up in the coming week as below output.
https://learn.microsoft.com/en-us/azure/databricks/sql/language-manual/sql-ref-variables
