### ISSUE TITLE
False positive validations

### ISSUE THREAD

**Issue by derekyidd** [databrickslabs/remorph#167]
Given:
select customer_id as c_id from staging_table where c_id is not null

We expect that the validation step would fail as we can't use c_id in the where statement.

It looks like when the table or view does not exist, we just pass the validation step.

Is it possible to validate even if the tables do not exist?

**Comment by sundarshankar89** [comment]
@derekyidd this has been a big challenge for us, we are coming up with a newer validation framework as part of our roadmap, which is few months down the line, however current lca warning should highlight this row as well. Let me know if this doesn't cc: @bishwajit-db

**Comment by bishwajit-db** [comment]
@derekyidd currently the tool generates a warning message in the error log file. 
![image](https://github.com/databrickslabs/remorph/assets/147722855/c8c89bb4-957d-4a8e-abe9-c20804646797)

**Comment by derekyidd** [comment]
This should also be logged in the docs somewhere about validation mode requiring the table to exist in the catalog in order to make accurate validations.

**Comment by sundarshankar89** [comment]
Sure @derekyidd we will add a FAQ.

**Comment by bishwajit-db** [comment]
The LCA issue has been resolved in PR #219 . The false positives in validation can be taken as a separate issue.
