### ISSUE TITLE
[LCA] Alias scoping issue

### ISSUE THREAD

**Issue by derekyidd** [databrickslabs/remorph#179]
Given the following Snowflake SQL:
SELECT column_a as customer_id
FROM mytable
WHERE **customer_id** = '123'

The following Spark SQL should be returned because of the different alias scoping used in Spark SQL
SELECT column_a as customer_id
FROM mytable
WHERE **column_a** = '123'

**Comment by sundarshankar89** [comment]
Currently, the scope is limited to a warning from the transpiler, as the column_a can be further an expression of any type. We are exploring details.
 
cc: @bishwajit-db @nsenno-dbr

**Comment by bishwajit-db** [comment]
@derekyidd LCA error has been resolved in PR #219
