### ISSUE TITLE
Support for Subquery during Transpilation

### ISSUE THREAD

**Issue by changshilim-db** [databrickslabs/remorph#187]
Description: During transpiliation, an error is raised whenever there is a subquery

Exception: 'Expected table name but got <Token token_type: TokenType.L_PAREN, text: (
Error: ParserError(file_name='/Workspace/Users/XXX/tools/sf_tasks/XX.sql', exception=ParseError("Expected table name but got <Token token_type: TokenType.L_PAREN, text: (, line: 116, col: 6, start: 5440, end: 5440, comments: []>
Expected output: Transpiler should transpile subquery as well

**Comment by sundarshankar89** [comment]
@changshilim-db can you share an example to reproduce
