### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by abhishekvenkataram-db** [databrickslabs/remorph#205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Category of Bug / Issue

Other

### Current Behavior

Seems like the sdk_config flag has now been made mandatory and due to which I am unable to call the remorph function! 

Please see code below:

from databricks.labs.remorph.config import MorphConfig
from databricks.labs.remorph.transpiler.execute import morph
from databricks.sdk import WorkspaceClient
ws = WorkspaceClient()
# ws.config
def transpile_directory(input_path, output_path):
  config = MorphConfig(
          source=“snowflake”,
          input_sql=input_path,
          output_folder=output_path,
          skip_validation=True,
          **sdk_config=None**
      )
  status = morph(config)
  print(status)
  return status

This code worked perfectly fine on Thursday 28-Mar and is failing now today 1-April

Please see the error screenshot:

<img width="957" alt="image" src="https://github.com/databrickslabs/remorph/assets/113180360/c0c8b434-601c-4dc4-bc56-38395d47db7b">

### Operating System

macOS

### Version

latest via Databricks CLI

**Comment by ganeshdogiparthi-db** [comment]
The issue is because Pip install is using the main branch directly. 
Please use only the release wheel file because continuous developments are happening in the main branch.

The issue is resolved after using the release wheel file instead of branch.
