### ISSUE TITLE
[BUG]: 'Builder' object has no attribute 'sdk_config'

### ISSUE THREAD

**Issue by abhishekvenkataram-db** [databrickslabs/remorph#207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Category of Bug / Issue

Other

### Current Behavior

The current remorph tool in the main branch requires two arguments to be passed for the morph function. But passing these and then trying to run the function results error mentioned in Relevant log output or Exception details

### Expected Behavior

Should be able to run the morph function after passing the two mandatory arguments

### Steps To Reproduce

1. Install remorph from main branch : %pip install -U git+https://github.com/databrickslabs/remorph.git@main
2. Restart python : dbutils.library.restartPython()
3. Declare below function to call remorph 

from databricks.labs.remorph.config import MorphConfig
from databricks.labs.remorph.transpiler.execute import morph

from databricks.sdk import WorkspaceClient

ws = WorkspaceClient()

# ws.config
def transpile_directory(input_path, output_path):
  config = MorphConfig(
          source="snowflake",
          input_sql=input_path, 
          output_folder=output_path,
          skip_validation=True,
          sdk_config=ws.config
      )

  status = morph(ws, config)
  print(status)
  return status
4. Run this command to recreate the error after creating the input and output paths : status = transpile_directory(input_path, db_sql_output_path)

Error screenshot : 
<img width="600" alt="image" src="https://github.com/databrickslabs/remorph/assets/113180360/4c1eafab-8c7d-41dd-b852-b2a891018a5a">

### Relevant log output or Exception details

```shell
AttributeError: 'Builder' object has no attribute 'sdk_config'
File <command-2718250924714079>, line 1
----> 1 status = transpile_directory(input_path, db_sql_output_path)
File /local_disk0/.ephemeral_nfs/envs/pythonEnv-9d7dbd04-3f57-4b15-9cd2-497126bd0ac7/lib/python3.10/site-packages/databricks/labs/lsql/backends.py:242, in DatabricksConnectBackend.__init__(self, ws)
    236 try:
    237     # pylint: disable-next=import-outside-toplevel
    238     from databricks.connect import (  # type: ignore[import-untyped]
    239         DatabricksSession,
    240     )
--> 242     spark = DatabricksSession.builder.sdk_config(ws.config).getOrCreate()
    243     super().__init__(spark, ws.config.debug_truncate_bytes)
    244 except ImportError as e:
```

### Operating System

macOS

### Version

latest via Databricks CLI

**Comment by sundarshankar89** [comment]
depends on https://github.com/databrickslabs/lsql/pull/86

**Comment by sundarshankar89** [comment]
@abhishekvenkataram-db  please of confirm you don't run into this issue when using latest release.
