### ISSUE TITLE
[FEATURE]: Create subcommand to generate lineage 

### ISSUE THREAD

**Issue by sundarshankar89** [databrickslabs/remorph#220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

Given a folder name as input generate lineage and expose them as dot file 

### Proposed Solution

NA

**Comment by raffifu** [comment]
Hii, i would like to works on this issue. Can you give more information about the requirements for generated lineage? is it a lineage of SQL file? Also, is there any example for the exported dot files?
