### ISSUE TITLE
[FEATURE]: Improve `ranking_windowed_function` rule in Snowflake grammar

### ISSUE THREAD

**Issue by vil1** [databrickslabs/remorph#258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

The rules for window functions, defined in `ranking_windowed_function` and its children is lacking:
- support for null ordering (`NULLS FIRST` / `NULLS LAST`) in its `ORDER BY` clause
- support for defining window frames (eg. `ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW`) in the `OVER` clause.

### Proposed Solution

There is some commented code in `SnowflakeParser.g4` that seems related to the missing bits described above

**Comment by jimidle** [comment]
I will take this one.

**Comment by jimidle** [comment]
I think it is best to do this by getting rid of all the myriad specifically specified functions in the grammar that are just standard function calls. However, that might cause quite a lot of changes in the Snowflake grammar and therefore the builders. I am not sure what the priority of Snowflake is vs TSQL? Equal? Lower? Higher?
