### ISSUE TITLE
Represent Template SQL as Expressions

### ISSUE THREAD

**Issue by sundarshankar89** [databrickslabs/remorph#264]
@ganeshdogiparthi-db you can read these queries in one dialect and covert them to other dialects. But keep these sources more readable.

_Originally posted by @nfx in https://github.com/databrickslabs/remorph/pull/216#discussion_r1572743310_

**Comment by jimidle** [comment]
Is this relevant now? We have ongoing works for TSQL in the area of expressions? Colse?
