### ISSUE TITLE
[FEATURE]: Improve Snowflake `predicate` grammar to accept NOT EXISTS expressions

### ISSUE THREAD

**Issue by vil1** [databrickslabs/remorph#273]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

The `predicate` grammar is currently defined as follow (definition edited for brevity)

```
predicate
    : EXISTS LR_BRACKET subquery RR_BRACKET
// more branches
```

And since there is no rule such as 

```
predicate
  : NOT predicate
```

Expressions containing `NOT EXISTS` are not accepted.

### Proposed Solution

Rephrase the `predicate` rule with

```
predicate
  : NOT? EXISTS LR_BRACKET subquery RR_BRACKET
```

Or

Add a `NOT predicate` branch to the `predicate` rule.

**Comment by jimidle** [comment]
PredicatePartial needs eliminating and the predicate rule implemented in the same way as TSQL, but with the relevant syntax changes

**Comment by jimidle** [comment]
The predicate grammar should be written as it is in TSQL, which will fix this and other issues. It is currently still using the poor style from the original poor gramamr.

**Comment by jimidle** [comment]
The proposed solution is not correct. TSQL does this, which is correct:

```antlr
searchCondition
    : LPAREN searchCondition RPAREN       # scPrec
    | NOT searchCondition                 # scNot
    | searchCondition AND searchCondition # scAnd
    | searchCondition OR searchCondition  # scOr
    | predicate                           # scPred
    ;

predicate
    : EXISTS LPAREN selectStatement RPAREN                                           # predExists
    | freetextPredicate                                                              # predFreetext
    | expression comparisonOperator expression                                       # predBinop
    | expression comparisonOperator (ALL | SOME | ANY) LPAREN selectStatement RPAREN # predASA
    | expression NOT? BETWEEN expression AND expression                              # predBetween
    | expression NOT? IN LPAREN (selectStatement | expressionList) RPAREN            # predIn
    | expression NOT? LIKE expression (ESCAPE expression)?                           # predLike
    | expression IS NOT? NULL                                                        # predIsNull
    | expression                                                                     # predExpression
    ;
```

We should eliminate predicatePartial and see why it currently is put in `expr` as I do not think it should be there - I think it is trying to process `AND` and `OR`there. The generated parser will be much better using the above approach.
