### ISSUE TITLE
[FEATURE]: Use POSEXPLODE when Snowflake SQL query requires index info

### ISSUE THREAD

**Issue by derekyidd** [databrickslabs/remorph#299]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

When given the following SQL:

SELECT 
  verticals.index AS index,    -- Accessing the index directly from the alias
  verticals.value AS value
FROM sample_data,
LATERAL FLATTEN(input => array_column, OUTER => TRUE ) AS verticals;  -- Aliasing FLATTEN as 'verticals'

remorph's translation uses to LATERAL VIEW OUTER EXPLODE. However, this does not produce index information like in Snowflake and will produce a query that fails.

### Proposed Solution

remorph should parse the query to find if ".index" is being used. If so, replace LATERAL VIEW OUTER EXPLODE with LATERAL VIEW OUTER POSEXPLODE. Use "pos" alias for the index and replace it. Use old alias for the value and replace ".value" instances.

SELECT 
  pos AS index,    -- pos represents the index of the element in the array
  verticals AS value
FROM sample_data
LATERAL VIEW POSEXPLODE(array_column) as pos, verticals;

**Comment by bishwajit-db** [comment]
@derekyidd The changes are in the main branch. Let us know if it works for you.

**Comment by derekyidd** [comment]
@bishwajit-db yes! Thank you! When will this be in the next release? Or will it already be in 0.1.6?

**Comment by derekyidd** [comment]
@bishwajit-db Yes! Thank you! Will this be in the next release 0.1.7 or is it already added to 0.1.6?

**Comment by sundarshankar89** [comment]
@derekyidd this fix should be already in 0.17.
