### ISSUE TITLE
[FEATURE]: Revamp the reconcile.constants.py

### ISSUE THREAD

**Issue by ravit-db** [databrickslabs/remorph#313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

The constants file has few un-used elements and need some restructuring.

### Proposed Solution

Remove redundant constants.
Restructure the constants.

**Comment by sundarshankar89** [comment]
Duplicate as #311 @ravit-db  you can close one of them

**Comment by ravit-db** [comment]
Duplicated with #311
