### ISSUE TITLE
[BUG]: Aggregation reconciliation is failing abruptly 

### ISSUE THREAD

**Issue by ganeshdogiparthi-db** [databrickslabs/remorph#789]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Category of Bug / Issue

ReconcileError

### Current Behavior

Aggregation reconciliation is failing with below error 

TypeError: reduce() of empty iterable with no initial value
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File <command-2032780391429444>, line 8
      4   return reduce(lambda agg_df, df: agg_df.unionByName(df), df_list)
      7 df = spark.sql("select * from data.testing.telecommunication_data")
----> 8 _union_dataframes([]).display()

File <command-2032780391429444>, line 4, in _union_dataframes(df_list)
      3 def _union_dataframes(df_list: list[DataFrame]) -> DataFrame:
----> 4   return reduce(lambda agg_df, df: agg_df.unionByName(df), df_list)

### Operating System

macOS

### Version

latest via Databricks CLI

**Comment by vijaypavann-db** [comment]
Handled in #740
