### ISSUE TITLE
[BUG]: Typo in test case should make it fail, but doesn't

### ISSUE THREAD

**Issue by vil1** [databrickslabs/remorph#811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Category of Bug / Issue

TranspileValidationError

### Current Behavior

The test case in `resources/functional/snowflake/test_monthname/test_monthname_7.sql` reads as follows:

```

-- snowflake sql:
SELECT TO_DATE('2015.03.04', 'yyyy.dd.MM') AS MON;

-- databricks sql:
SELECT TO_DATE('2015.03.04', 'yyyy.d.MM') AS MON;

```
With an obvious typo (the time format `yyyy.dd.MM` becomes `yyyy.d.MM`).

However, the fact that CI passes on `remorph-py` despite of that typo implies one of the three following possibilities:
- I do not understand date-time patterns correctly and snowflake's `yyyy.dd.MM` should actually be translated to `yyyy.d.MM`, in which case we can close this issue.
- `remorph-py` incorrectly translates `yyyy.dd.MM` to `yyyy.d.MM`, causing said test to pass even though this behaviour is (AFAIK) incorrect, in which case `remorph-py` has to be fixed in that respect.
- said test is somehow skipped during CI and/or fails silently, in which case we need to conduct a deeper investigation to understand why this is the case and whether other tests are affected.

### Expected Behavior

We should make sure that the aforementioned test case fails (as expected) on `remorph-py`, and then make sure that it passes once the typo is fixed.

### Operating System

macOS

### Version

latest via Databricks CLI

**Comment by ericvergnaud** [comment]
Already fixed, see PR #1287

![Image](https://github.com/user-attachments/assets/95fb134b-42bf-4f1e-8117-7859f955f2b1)
