### ISSUE TITLE
[BUG]: SHA2 function is not having the digest size if it is not specified

### ISSUE THREAD

**Issue by pamons-databricks** [databrickslabs/remorph#951]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Category of Bug / Issue

TranspileValidationError

### Current Behavior

select sha2(test_col) from test_tbl

### Expected Behavior

select sha2(test_col, 256) from test_tbl

### Steps To Reproduce

If the digest size is not specified in a Snowflake query using SHA2, Snowflake will use 256 as the default.
In Databricks a digest size must be specified.
When transpile is being run on a Snowflake script if a sha2 function does not have its digest size specified it should be added, defaulting to 256 to match Snowflake.

### Sample Query

```shell
select sha2(test_col) from test_tbl
```

### Operating System

macOS

### Version

latest via Databricks CLI

**Comment by ganeshdogiparthi-db** [comment]
Closes PR #1279
